test_that("See if we can load in our datasets", {
    data(enUSxgaCMU, enUSxgaCainteoir, enGBxrpCainteoir, enScotlandCainteoir, arpabet)
    expect_equal(enUSxgaCMU[1, "word"], "'bout")
    expect_equal(enUSxgaCMU[1, "pronunciation"], "B AW1 T")
    expect_equal(enUSxgaCainteoir[1, "word"], "a")
    expect_equal(enUSxgaCainteoir[1, "pronunciation"], "AX")
    expect_equal(enGBxrpCainteoir[1, "word"], "a")
    expect_equal(enGBxrpCainteoir[1, "pronunciation"], "AX")
    expect_equal(enScotlandCainteoir[1, "word"], "a")
    expect_equal(enScotlandCainteoir[1, "pronunciation"], "EY1")
    expect_equal(arpabet[1, "arpabet"], "-")
    expect_equal(arpabet[1, "ipa"], "")
    expect_equal(arpabet[1, "xsampa"], "-")
})
